base:
  image: cgcgbcbc/spark
  dns_search: node.lab.mu
  restart: always
master:
  extends:
    file: docker-compose.yml
    service: base
  hostname: master-spark.node.lab.mu
  environment:
    SERVICE_NAME: master-spark
    SERVICE_TAGS: spark,master

slave:
  extends:
    file: docker-compose.yml
    service: base
  hostname: .node.lab.mu
  environment:
    master: master-spark.node.lab.mu
    SERVICE_NAME: slave-spark
    SERVICE_TAGS: spark,slave
  command: /worker.sh

shell:
  extends:
    file: docker-compose.yml
    service: base
  command: /spark/bin/spark-shell --master spark://master-spark:7077
